pipeline {
    agent {
        docker 'docker.internal.kevinlin.info/infra/ci-base:0.0.6'
    }

    stages {
        stage('Install') {
            steps {
                sh 'npm-s3 install'
            }
        }
        stage('Test') {
            parallel {
                stage('Build') {
                    environment {
                        NODE_ENV = 'production'
                        CLIENT_SENTRY_DSN = credentials('react-elemental-docs--sentry-dsn')
                        PIWIK_URL = 'https://analytics.kevinlin.info'
                        PIWIK_SITE_ID = '4'
                        PIWIK_CLIENT_TRACKER_NAME = 'client'
                        PIWIK_SERVER_TRACKER_NAME = 'server'
                        REACT_ELEMENTAL_VERSION = sh(
                            script: 'cat package.json | jq -r \'.dependencies[\"react-elemental\"]\'',
                            returnStdout: true
                        ).trim()
                    }
                    steps {
                        sh 'npm run build'
                    }
                }
                stage('Lint') {
                    steps {
                        sh 'npm run lint'
                    }
                }
                stage('Unit') {
                    steps {
                        sh 'npm run test'
                    }
                }
            }
        }
    }

    post {
        always {
            archive 'dist/index.html'
            deleteDir()
        }
    }
}
