pipeline {
    agent {
        docker {
            image 'docker.internal.kevinlin.info/infra/ci-base:0.1.0'
            label 'docker-executor'
            args '-v $EXECUTOR_SSH_DIR:$CONTAINER_SSH_DIR:ro'
        }
    }

    stages {
        stage('Install') {
            steps {
                sh 'npm-s3 install'
            }
        }
        stage('Test') {
            parallel {
                stage('Build') {
                    environment {
                        NODE_ENV = 'production'
                        CLIENT_SENTRY_DSN = credentials('react-elemental-docs--sentry-dsn')
                        ROUTING_BASE_PATH = '/react-elemental-docs'
                        PIWIK_URL = 'https://analytics.kevinlin.info'
                        PIWIK_SITE_ID = '4'
                        PIWIK_CLIENT_TRACKER_NAME = 'client'
                        PIWIK_SERVER_TRACKER_NAME = 'server'
                        REACT_ELEMENTAL_VERSION = sh(
                            script: 'cat package.json | jq -r \'.dependencies[\"react-elemental\"]\'',
                            returnStdout: true
                        ).trim()
                    }
                    steps {
                        sh 'npm run build'
                    }
                }
                stage('Lint') {
                    steps {
                        sh 'npm run lint'
                    }
                }
                stage('Unit') {
                    steps {
                        sh 'npm run test'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'mv dist /tmp/react-elemental-docs'
                sh 'git fetch --all'
                sh 'git checkout gh-pages'
                sh 'git reset --hard origin/gh-pages'
                sh 'mv /tmp/react-elemental-docs/index.html index.html'
                sh 'cp index.html 404.html'
                sh 'git add .'
                sh 'git status'
                sh "git commit -m \"[automatic commit] ${GIT_BRANCH}:${GIT_COMMIT}\" || :"
                sh 'git remote add github git@github.com:LINKIWI/react-elemental-docs.git'
                sh 'git push origin HEAD'
                sh 'git push github HEAD'
            }
        }
    }

    post {
        success {
            archive 'index.html'
        }
    }
}
