pipeline {
    agent {
        docker {
            image 'docker.internal.kevinlin.info/infra/ci-base:0.2.6'
            label 'docker-executor'
        }
    }

    options {
        withAWS(
            endpointUrl: 'https://storage.kevinlin.info',
            credentials: 'storage-internal',
        )
    }

    stages {
        stage('Environment') {
            steps {
                s3Download(
                    bucket: 'internal',
                    path: 'resources/react-elemental-docs/.env',
                    file: '.env',
                )
            }
        }
        stage('Install') {
            steps {
                sh 'npm-s3 install'
            }
        }
        stage('Test') {
            parallel {
                stage('Lint') {
                    steps {
                        sh 'npm run lint'
                    }
                }
                stage('Unit') {
                    steps {
                        sh 'npm run test'
                    }
                }
            }
        }
        stage('Build') {
            environment {
                NODE_ENV = 'production'
                GIT_SHA = "$GIT_COMMIT"
                REACT_ELEMENTAL_VERSION = sh(
                    script: 'cat package.json | jq -r \'.dependencies[\"react-elemental\"]\'',
                    returnStdout: true
                ).trim()
            }
            steps {
                sh 'npm run build'
            }
        }
        stage('Release') {
            steps {
                sh 'cp dist/index.html .'
                sh 'cp dist/index.html 404.html'
                sh 'tar -czf release.tar.gz index.html 404.html'
                s3Upload(
                    bucket: 'internal',
                    path: "deploy/${env.JOB_NAME}/${env.GIT_COMMIT}/",
                    file: 'release.tar.gz',
                )
            }
        }
        stage('Deploy') {
            steps {
                build(
                    job: 'task--static-deploy',
                    parameters: [
                        string(name: 'RELEASE_ARTIFACT', value: "${env.JOB_NAME}"),
                        string(name: 'RELEASE_VERSION', value: "${env.GIT_COMMIT}"),
                        string(name: 'DOMAIN', value: 'react-elemental-docs.static.kevinlin.info'),
                        string(name: 'GIT_REMOTE_INTERNAL', value: "${env.GIT_URL}"),
                        string(name: 'GIT_REMOTE_GITHUB', value: 'git@github.com:LINKIWI/react-elemental-docs-static.git'),
                    ],
                    wait: true,
                )
            }
        }
    }
}
